import type { RenderSpec } from "./renderSpec/types";

// Mock render spec for the Ditto TikTok ad.
// This simulates what video-decomposition-engine would output.
export const dittoMockSpec: RenderSpec = {
  specVersion: "1.0",
  videoId: "ditto-campus-dating",
  title: "Ditto Campus Dating Ad",
  fps: 30,
  width: 1080,
  height: 1920,
  scenes: [
    {
      sceneId: "scene_1",
      label: "Hook — direct address",
      role: "hook",
      durationSec: 3,
      visualType: "captured_video",
      audioStrategy: "use_original",
      assetRefs: ["hook_clip"],
      subtitleText: "Okay, real talk.",
      structuralPurpose: "attention_grab",
    },
    {
      sceneId: "scene_2",
      label: "Problem — campus dating is hard",
      role: "problem",
      durationSec: 3,
      visualType: "text_motion",
      audioStrategy: "tts",
      assetRefs: [],
      subtitleText: "I didn't think campus dating could be this easy.",
      voiceoverText: "I didn't think campus dating could be this easy.",
      structuralPurpose: "problem_setup",
    },
    {
      sceneId: "scene_3",
      label: "Solution reveal — Ditto intro",
      role: "solution_reveal",
      durationSec: 4,
      visualType: "motion_graphic_card",
      audioStrategy: "tts",
      assetRefs: ["screenshot_1"],
      subtitleText: "Ditto is insane!",
      voiceoverText: "Ditto is insane! You just type it in your browser.",
      structuralPurpose: "solution_introduction",
    },
    {
      sceneId: "scene_4",
      label: "How it works — app demo",
      role: "how_it_works",
      durationSec: 4,
      visualType: "ui_walkthrough",
      audioStrategy: "tts",
      assetRefs: ["screenshot_1", "screenshot_2", "screenshot_3"],
      subtitleText: "It plans the whole date for you!",
      voiceoverText: "You just type it in your browser, and it plans the whole date for you!",
      structuralPurpose: "feature_demonstration",
    },
    {
      sceneId: "scene_5",
      label: "CTA — human close",
      role: "human_cta",
      durationSec: 3,
      visualType: "captured_video",
      audioStrategy: "use_original",
      assetRefs: ["cta_clip"],
      subtitleText: "You have to check this out!",
      structuralPurpose: "call_to_action",
    },
  ],
  audio: {
    voiceoverFile: "voiceover",
    captionsFile: "captions",
  },
};
